import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Styles from "./page.module.css";
import "bootstrap/dist/css/bootstrap.min.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ul>
          <li className={Styles.list}>
            <Link href="/">Home</Link>
            <Link href="/about">About Me</Link>
            <Link href="/projects">My Projects</Link>
            <Link href="/contact">Contact</Link>
          </li>
        </ul>
        {children}
      </body>
    </html>
  );
}
