const ADDNEWTASK = "ADDNEWTASK";

const SHOWMODAL = "SHOWMODAL";

const HIDEMODAL = "HIDEMODAL";

const UPDATETASK = "UPDATETASK";

const DELETETASK = "DELETETASK";

const FILTREDTASK = "FILTREDTASK";
export {
  ADDNEWTASK,
  SHOWMODAL,
  HIDEMODAL,
  UPDATETASK,
  DELETETASK,
  FILTREDTASK,
};
